name: Cloud Function Deploy Workflow

on:
  push:
    branches:
      - master

jobs:
  deploy-google-cloud-function:
    runs-on: ubuntu-latest
    env:
      REGION: europe-west1
      PROJECT_ID: hao-wang-solita-lab
      FUNCTION_NAME: Cloud-Function-SubscribeToTopic
      ENTRYPOINT: functions.SubscribeToTopic
      TOPIC_NAME: product_arrangement_event_topic
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt
      - uses: axel-op/package-java-google-cloud-function@main
        id: package
      - name: Authenticate on Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: '${{ secrets.GCP_SA_SECRET }}'
      - name: Deploy on Google Cloud
        id: deploy
        uses: google-github-actions/deploy-cloud-functions@v2
        with:
          name: ${{ env.FUNCTION_NAME }}
          region: ${{ env.REGION }}
          source_dir: ${{ steps.package.outputs.deployment-directory }}
          entry_point: ${{ env.ENTRYPOINT }}
          event_trigger_type: 'google.pubsub.topic.publish'
          event_trigger_resource: 'projects/${{ env.PROJECT_ID}}/topics/${{ env.TOPIC_NAME}}'
          event_trigger_service: pubsub.googleapis.com
          runtime: java17